compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 4  # Change this to your number of GPUs
gpu_ids: 0,1,2,3  # Change this to your GPU IDs
machine_rank: 0
num_machines: 1
main_training_function: main
mixed_precision: bf16  # Use bf16 for better performance
use_cpu: false
debug: false
dynamo_backend: "INDUCTOR"  # For optimization
same_network: true
rdzv_backend: static 